[2025-03-18T18:33:56.793+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-18T18:33:57.000+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_dbt_clean_reviews_pipeline.dbt_run scheduled__2025-02-02T00:00:00+00:00 [queued]>
[2025-03-18T18:33:57.148+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_dbt_clean_reviews_pipeline.dbt_run scheduled__2025-02-02T00:00:00+00:00 [queued]>
[2025-03-18T18:33:57.149+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-18T18:33:57.888+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): dbt_run> on 2025-02-02 00:00:00+00:00
[2025-03-18T18:33:57.920+0000] {standard_task_runner.py:72} INFO - Started process 29945 to run task
[2025-03-18T18:33:57.938+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_dbt_clean_reviews_pipeline', 'dbt_run', 'scheduled__2025-02-02T00:00:00+00:00', '--job-id', '1151', '--raw', '--subdir', 'DAGS_FOLDER/dag_load_reviews.py', '--cfg-path', '/tmp/tmpkhf72dfr']
[2025-03-18T18:33:57.940+0000] {standard_task_runner.py:105} INFO - Job 1151: Subtask dbt_run
[2025-03-18T18:33:58.435+0000] {task_command.py:467} INFO - Running <TaskInstance: load_dbt_clean_reviews_pipeline.dbt_run scheduled__2025-02-02T00:00:00+00:00 [running]> on host DESKTOP-IM7V4RI.
[2025-03-18T18:33:59.272+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohammed' AIRFLOW_CTX_DAG_ID='load_dbt_clean_reviews_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-02T00:00:00+00:00'
[2025-03-18T18:33:59.277+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-18T18:33:59.288+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-18T18:33:59.290+0000] {logging_mixin.py:190} INFO - Current task name:dbt_run state:running start_date:2025-03-18 18:33:57.001297+00:00
[2025-03-18T18:33:59.298+0000] {logging_mixin.py:190} INFO - Dag name:load_dbt_clean_reviews_pipeline and current dag run status:running
[2025-03-18T18:33:59.299+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-18T18:33:59.301+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-18T18:33:59.303+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/mohammed/.dbt/dbt_projects/bank_reviews_transactional && dbt run']
[2025-03-18T18:33:59.377+0000] {subprocess.py:99} INFO - Output:
[2025-03-18T18:34:23.213+0000] {subprocess.py:106} INFO - [0m18:34:23  Running with dbt=1.9.3
[2025-03-18T18:34:27.284+0000] {subprocess.py:106} INFO - [0m18:34:27  Registered adapter: postgres=1.9.0
[2025-03-18T18:34:30.612+0000] {subprocess.py:106} INFO - [0m18:34:30  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-03-18T18:34:30.614+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-03-18T18:34:30.614+0000] {subprocess.py:106} INFO - - models.bank_reviews_transactional.transactional
[2025-03-18T18:34:31.767+0000] {subprocess.py:106} INFO - [0m18:34:31  Found 1 model, 1 source, 433 macros
[2025-03-18T18:34:31.781+0000] {subprocess.py:106} INFO - [0m18:34:31
[2025-03-18T18:34:31.804+0000] {subprocess.py:106} INFO - [0m18:34:31  Concurrency: 4 threads (target='dev')
[2025-03-18T18:34:31.809+0000] {subprocess.py:106} INFO - [0m18:34:31
[2025-03-18T18:34:33.417+0000] {subprocess.py:106} INFO - [0m18:34:33  1 of 1 START sql table model transactional.clean_reviews ....................... [RUN]
[2025-03-18T18:34:36.241+0000] {subprocess.py:106} INFO - [0m18:34:36  1 of 1 OK created sql table model transactional.clean_reviews .................. [[32mSELECT 549[0m in 2.81s]
[2025-03-18T18:34:36.376+0000] {subprocess.py:106} INFO - [0m18:34:36
[2025-03-18T18:34:36.378+0000] {subprocess.py:106} INFO - [0m18:34:36  Finished running 1 table model in 0 hours 0 minutes and 4.56 seconds (4.56s).
[2025-03-18T18:34:36.570+0000] {subprocess.py:106} INFO - [0m18:34:36
[2025-03-18T18:34:36.597+0000] {subprocess.py:106} INFO - [0m18:34:36  [32mCompleted successfully[0m
[2025-03-18T18:34:36.598+0000] {subprocess.py:106} INFO - [0m18:34:36
[2025-03-18T18:34:36.598+0000] {subprocess.py:106} INFO - [0m18:34:36  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-03-18T18:34:49.398+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-18T18:34:50.263+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-18T18:34:50.270+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=load_dbt_clean_reviews_pipeline, task_id=dbt_run, run_id=scheduled__2025-02-02T00:00:00+00:00, execution_date=20250202T000000, start_date=20250318T183357, end_date=20250318T183450
[2025-03-18T18:34:50.598+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-18T18:34:50.599+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-18T18:34:50.600+0000] {logging_mixin.py:190} INFO - Dag name:load_dbt_clean_reviews_pipeline queued_at:2025-03-18 18:33:49.117315+00:00
[2025-03-18T18:34:50.600+0000] {logging_mixin.py:190} INFO - Task hostname:DESKTOP-IM7V4RI. operator:BashOperator
[2025-03-18T18:34:50.687+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-18T18:34:50.907+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-18T18:34:51.090+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-18T18:34:51.125+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
