[2025-03-17T19:12:04.676+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T19:12:04.703+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_store_reviews.scrape_and_insert_data_to_json manual__2025-03-17T19:12:01.876828+00:00 [queued]>
[2025-03-17T19:12:04.710+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_store_reviews.scrape_and_insert_data_to_json manual__2025-03-17T19:12:01.876828+00:00 [queued]>
[2025-03-17T19:12:04.711+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-17T19:12:04.727+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): scrape_and_insert_data_to_json> on 2025-03-17 19:12:01.876828+00:00
[2025-03-17T19:12:04.737+0000] {standard_task_runner.py:72} INFO - Started process 986631 to run task
[2025-03-17T19:12:04.741+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'scrape_and_store_reviews', 'scrape_and_insert_data_to_json', 'manual__2025-03-17T19:12:01.876828+00:00', '--job-id', '683', '--raw', '--subdir', 'DAGS_FOLDER/scrape_and_store_reviews.py', '--cfg-path', '/tmp/tmpa6rgqpyu']
[2025-03-17T19:12:04.742+0000] {standard_task_runner.py:105} INFO - Job 683: Subtask scrape_and_insert_data_to_json
[2025-03-17T19:12:04.816+0000] {task_command.py:467} INFO - Running <TaskInstance: scrape_and_store_reviews.scrape_and_insert_data_to_json manual__2025-03-17T19:12:01.876828+00:00 [running]> on host DESKTOP-IM7V4RI.
[2025-03-17T19:12:04.946+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='scrape_and_store_reviews' AIRFLOW_CTX_TASK_ID='scrape_and_insert_data_to_json' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T19:12:01.876828+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-17T19:12:01.876828+00:00'
[2025-03-17T19:12:04.949+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-17T19:12:04.950+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-17T19:12:04.950+0000] {logging_mixin.py:190} INFO - Current task name:scrape_and_insert_data_to_json state:running start_date:2025-03-17 19:12:04.703775+00:00
[2025-03-17T19:12:04.950+0000] {logging_mixin.py:190} INFO - Dag name:scrape_and_store_reviews and current dag run status:running
[2025-03-17T19:12:04.950+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-17T19:12:04.954+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 763, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/airflow/scripts/insert_data_to_json.py", line 5, in insert_data_to_json
    scraped_data = scrape_bank_reviews()
                   ^^^^^^^^^^^^^^^^^^^
NameError: name 'scrape_bank_reviews' is not defined
[2025-03-17T19:12:05.010+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-17T19:12:05.010+0000] {logging_mixin.py:190} INFO - Task start:2025-03-17 19:12:04.703775+00:00 end:2025-03-17 19:12:05.006519+00:00 duration:0.302744
[2025-03-17T19:12:05.010+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): scrape_and_insert_data_to_json> dag:<DAG: scrape_and_store_reviews> dagrun:<DagRun scrape_and_store_reviews @ 2025-03-17 19:12:01.876828+00:00: manual__2025-03-17T19:12:01.876828+00:00, state:running, queued_at: 2025-03-17 19:12:02.037238+00:00. externally triggered: True>
[2025-03-17T19:12:05.011+0000] {logging_mixin.py:190} INFO - Failure caused by name 'scrape_bank_reviews' is not defined
[2025-03-17T19:12:05.011+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_and_store_reviews, task_id=scrape_and_insert_data_to_json, run_id=manual__2025-03-17T19:12:01.876828+00:00, execution_date=20250317T191201, start_date=20250317T191204, end_date=20250317T191205
[2025-03-17T19:12:05.092+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-17T19:12:05.092+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 683 for task scrape_and_insert_data_to_json (name 'scrape_bank_reviews' is not defined; 986631)
Traceback (most recent call last):
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 763, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/airflow/scripts/insert_data_to_json.py", line 5, in insert_data_to_json
    scraped_data = scrape_bank_reviews()
                   ^^^^^^^^^^^^^^^^^^^
NameError: name 'scrape_bank_reviews' is not defined
[2025-03-17T19:12:05.119+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-17T19:12:05.158+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-17T19:12:05.166+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
